export const OPPORTUNITIES = [
  {
    id: '1',
    title: 'Национальная олимпиада по математике',
    category: 'Олимпиада',
    format: 'Очно',
    deadline: '2025-09-15',
    grade_min: 9,
    grade_max: 11,
    description: 'Ежегодная олимпиада по математике для старшеклассников Казахстана. Победители получают право участия на международном уровне и стипендии.',
    requirements: 'Ученики 9–11 классов, казахстанское гражданство',
    apply_url: 'https://example.com/math-olympiad',
    tags: ['STEM', 'Математика', 'Олимпиада'],
    image: '🏆',
  },
  {
    id: '2',
    title: 'Хакатон MIT SOLVE Youth Challenge',
    category: 'Хакатон',
    format: 'Онлайн',
    deadline: '2025-10-01',
    grade_min: 8,
    grade_max: 11,
    description: 'Международный хакатон для молодёжи. Нужно решить одну из глобальных проблем с помощью технологий. Призовой фонд $10 000.',
    requirements: 'Команды 2–5 человек, возраст 13–18 лет',
    apply_url: 'https://example.com/mit-solve',
    tags: ['Программирование', 'STEM', 'Хакатон'],
    image: '💻',
  },
  {
    id: '3',
    title: 'Стипендия Болашак',
    category: 'Стипендия',
    format: 'Очно',
    deadline: '2025-11-30',
    grade_min: 11,
    grade_max: 11,
    description: 'Президентская стипендия Казахстана для обучения в лучших университетах мира. Полное финансирование.',
    requirements: 'Выпускники 11 класса, GPA 4.5+, IELTS 6.5+',
    apply_url: 'https://example.com/bolashak',
    tags: ['Стипендия', 'Поступление'],
    image: '🎓',
  },
  {
    id: '4',
    title: 'Летняя школа по физике CERN',
    category: 'Летняя школа',
    format: 'Очно',
    deadline: '2025-08-20',
    grade_min: 10,
    grade_max: 11,
    description: 'Двухнедельная интенсивная программа в CERN, Женева. Лекции от учёных, эксперименты на коллайдере.',
    requirements: 'Ученики 10–11 классов, знание физики на высоком уровне, английский B2+',
    apply_url: 'https://example.com/cern',
    tags: ['STEM', 'Наука', 'Физика'],
    image: '⚛️',
  },
  {
    id: '5',
    title: 'Young Entrepreneurs Business Challenge',
    category: 'Конкурс',
    format: 'Онлайн',
    deadline: '2025-09-30',
    grade_min: 8,
    grade_max: 11,
    description: 'Международный конкурс бизнес-планов для школьников. Менторство от предпринимателей, шанс получить инвестиции.',
    requirements: 'Команды 2–4 человека, любая страна',
    apply_url: 'https://example.com/yebc',
    tags: ['Бизнес', 'Финансы'],
    image: '💼',
  },
  {
    id: '6',
    title: 'Программа исследований NASA Space School',
    category: 'Исследования',
    format: 'Онлайн',
    deadline: '2025-10-15',
    grade_min: 9,
    grade_max: 11,
    description: 'Шестинедельная онлайн-программа NASA для старшеклассников. Изучение космических технологий, работа с реальными данными.',
    requirements: 'Английский B1+, знание физики и математики',
    apply_url: 'https://example.com/nasa',
    tags: ['STEM', 'Наука', 'Исследования'],
    image: '🚀',
  },
  {
    id: '7',
    title: 'Волонтёрская программа UNICEF',
    category: 'Волонтёрство',
    format: 'Очно',
    deadline: '2025-08-31',
    grade_min: 8,
    grade_max: 11,
    description: 'Помощь детям в уязвимых ситуациях в Казахстане. Получение международного сертификата волонтёра.',
    requirements: 'Любой класс, желание помогать',
    apply_url: 'https://example.com/unicef',
    tags: ['Социальное влияние', 'Волонтёрство'],
    image: '🤝',
  },
  {
    id: '8',
    title: 'Олимпиада по программированию IOI',
    category: 'Олимпиада',
    format: 'Очно',
    deadline: '2025-12-01',
    grade_min: 8,
    grade_max: 11,
    description: 'Международная олимпиада по информатике — самый престижный конкурс по программированию для школьников.',
    requirements: 'Знание C++/Python, прохождение национального отбора',
    apply_url: 'https://example.com/ioi',
    tags: ['Программирование', 'STEM', 'Олимпиада'],
    image: '🖥️',
  },
  {
    id: '9',
    title: 'Стажировка в Kaspi Bank',
    category: 'Стажировка',
    format: 'Очно',
    deadline: '2025-09-01',
    grade_min: 10,
    grade_max: 11,
    description: 'Летняя стажировка в крупнейшем финтех-банке Казахстана. Опыт работы в IT, маркетинге или финансах.',
    requirements: 'Ученики 10–11 классов, Алматы',
    apply_url: 'https://example.com/kaspi',
    tags: ['Бизнес', 'Финансы', 'Стажировка'],
    image: '🏦',
  },
  {
    id: '10',
    title: 'Конкурс научных проектов Intel ISEF',
    category: 'Конкурс',
    format: 'Очно',
    deadline: '2025-11-01',
    grade_min: 9,
    grade_max: 11,
    description: 'Крупнейший мировой научный конкурс для школьников. Призы до $75 000. Проекты по всем научным дисциплинам.',
    requirements: 'Собственный научный проект, научный руководитель',
    apply_url: 'https://example.com/isef',
    tags: ['Наука', 'STEM', 'Исследования'],
    image: '🔬',
  },
]

export const COURSES = [
  {
    id: '1',
    title: 'Математика для олимпиад',
    description: 'Подготовка к математическим олимпиадам: комбинаторика, теория чисел, геометрия и алгебра на конкурсном уровне.',
    level: 'Продвинутый',
    tags: ['STEM', 'Математика'],
    image: '📐',
    lessons: [
      { id: '1-1', title: 'Теория чисел: делимость и НОД', content: 'В этом уроке мы изучим основы теории чисел: признаки делимости, наибольший общий делитель (НОД) и наименьшее общее кратное (НОК). Эти темы встречаются в большинстве олимпиад.\n\n**Ключевые понятия:**\n- Делимость: a делится на b, если существует целое c такое, что a = b×c\n- НОД(a,b) = произведение общих простых множителей\n- Алгоритм Евклида: НОД(a,b) = НОД(b, a mod b)\n\n**Пример задачи:** Найдите НОД(252, 198).\nРешение: 252 = 198×1 + 54; 198 = 54×3 + 36; 54 = 36×1 + 18; 36 = 18×2 + 0. Ответ: 18.', video_url: '', order_index: 1, quiz: { question: 'Чему равен НОД(48, 18)?', options: ['2', '6', '9', '12'], answer: 1 } },
      { id: '1-2', title: 'Комбинаторика: принцип счёта', content: 'Комбинаторика — раздел математики о подсчёте количества возможных конфигураций.\n\n**Формулы:**\n- Размещения: A(n,k) = n!/(n-k)!\n- Сочетания: C(n,k) = n!/(k!(n-k)!)\n- Перестановки: P(n) = n!\n\n**Правило суммы:** если A и B несовместимы, |A∪B| = |A| + |B|\n**Правило произведения:** если выбор A не зависит от B, всего вариантов |A|×|B|\n\n**Задача:** Сколькими способами можно выбрать 3 человека из 10?\nC(10,3) = 10!/(3!×7!) = 120', video_url: '', order_index: 2, quiz: { question: 'C(6,2) = ?', options: ['12', '15', '30', '36'], answer: 1 } },
      { id: '1-3', title: 'Неравенства: AM-GM и Коши-Буняковский', content: 'Неравенства — один из главных инструментов на олимпиадах.\n\n**Неравенство AM-GM:**\nДля неотрицательных чисел: (a₁+a₂+...+aₙ)/n ≥ (a₁·a₂·...·aₙ)^(1/n)\n\nЗнак равенства достигается, когда все числа равны.\n\n**Применение:** Найдите минимум f(x) = x + 4/x при x > 0.\nПо AM-GM: x + 4/x ≥ 2√(x·4/x) = 4. Минимум = 4 при x = 2.\n\n**Неравенство Коши-Буняковского:**\n(a₁b₁+...+aₙbₙ)² ≤ (a₁²+...+aₙ²)(b₁²+...+bₙ²)', video_url: '', order_index: 3, quiz: { question: 'При каком x достигается минимум x + 9/x (x > 0)?', options: ['1', '3', '9', '4.5'], answer: 1 } },
      { id: '1-4', title: 'Геометрия: окружности и углы', content: 'Планиметрия — ключевой раздел олимпиадной геометрии.\n\n**Теоремы об углах:**\n- Вписанный угол = половине центрального угла\n- Углы, вписанные в одну дугу, равны\n- Угол между касательной и хордой = вписанному углу\n\n**Теорема Фалеса:** угол, вписанный в полуокружность = 90°\n\n**Теорема Птолемея** (для вписанного четырёхугольника):\nAC·BD = AB·CD + AD·BC\n\nЭти теоремы позволяют решить большинство олимпиадных задач по геометрии.', video_url: '', order_index: 4, quiz: { question: 'Вписанный угол, опирающийся на диаметр, равен:', options: ['45°', '60°', '90°', '180°'], answer: 2 } },
    ]
  },
  {
    id: '2',
    title: 'Английский для академического успеха',
    description: 'Подготовка к IELTS/SAT, академическое письмо, чтение научных текстов и устная речь для поступления в университеты.',
    level: 'Средний',
    tags: ['Английский', 'Поступление'],
    image: '📚',
    lessons: [
      { id: '2-1', title: 'Academic Writing: структура эссе', content: 'Академическое эссе — основа поступления в зарубежные университеты.\n\n**Структура эссе IELTS Task 2:**\n1. **Introduction** (2-3 предложения): перефразируйте вопрос + thesis statement\n2. **Body Paragraph 1**: topic sentence + evidence + explanation + link\n3. **Body Paragraph 2**: topic sentence + evidence + explanation + link\n4. **Conclusion**: summary + final thought\n\n**Ключевые linking words:**\n- Добавление: Furthermore, Moreover, In addition\n- Контраст: However, Nevertheless, On the other hand\n- Причина: Therefore, As a result, Consequently\n\n**Типичные ошибки:** разговорный стиль, I think/I believe (замените на: It is argued that), слишком короткие параграфы.', video_url: '', order_index: 1, quiz: { question: 'What is a "thesis statement"?', options: ['The title of the essay', 'The main argument of the essay', 'A supporting example', 'The conclusion'], answer: 1 } },
      { id: '2-2', title: 'Reading Comprehension: стратегии IELTS', content: 'IELTS Reading — 60 минут, 3 текста, 40 вопросов. Скорость важна!\n\n**Стратегия Skimming:** быстро прочитайте текст (30 сек) чтобы понять главную идею каждого параграфа.\n\n**Стратегия Scanning:** ищите конкретные слова/числа — не читайте весь текст.\n\n**Типы вопросов:**\n- True/False/Not Given: осторожно — "Not Given" значит информация не упомянута\n- Matching Headings: читайте первое и последнее предложение параграфа\n- Fill in the Gap: ответ всегда есть в тексте дословно\n\n**Правило:** всегда читайте вопросы ПЕРЕД текстом.', video_url: '', order_index: 2, quiz: { question: 'What does "Not Given" mean in IELTS True/False/Not Given?', options: ['The statement is false', 'The statement contradicts the text', 'The information is not in the text', 'The question is invalid'], answer: 2 } },
      { id: '2-3', title: 'Vocabulary: академическая лексика', content: 'Academic Word List (AWL) — 570 слов, которые встречаются в 80% академических текстов.\n\n**10 самых важных слов AWL:**\n1. **analyze** — разбирать на части, исследовать\n2. **concept** — понятие, концепция\n3. **significant** — значительный, важный\n4. **approach** — подход, метод\n5. **evidence** — доказательство, свидетельство\n6. **constitute** — составлять, являться\n7. **factors** — факторы\n8. **identify** — определять, устанавливать\n9. **indicate** — указывать, свидетельствовать\n10. **process** — процесс; обрабатывать\n\n**Совет:** учите слова в контексте, не изолированно. Используйте Anki для повторений.', video_url: '', order_index: 3, quiz: { question: 'What does "significant" mean?', options: ['Small', 'Important', 'Complex', 'Recent'], answer: 1 } },
      { id: '2-4', title: 'Speaking: IELTS Part 2 — монолог', content: 'IELTS Speaking Part 2: вам дают карточку с темой, 1 минута на подготовку, 2 минуты на речь.\n\n**Структура PREP:**\n- **P**oint — назовите тему\n- **R**eason — объясните почему\n- **E**xample — приведите пример\n- **P**oint — завершите мысль\n\n**Пример карточки:** "Describe a book you enjoyed reading."\n- Point: "I\'d like to talk about \'The Little Prince\' by Antoine de Saint-Exupéry."\n- Reason: "I chose this book because it changed the way I think about life."\n- Example: "For instance, the idea that what\'s essential is invisible to the eye really resonated with me."\n- Point: "Overall, this book taught me to value imagination and human connections."\n\n**Частые ошибки:** паузы "um, uh" (замените на "well, actually"), говорить слишком тихо.', video_url: '', order_index: 4, quiz: { question: 'How long do you have to speak in IELTS Part 2?', options: ['1 minute', '2 minutes', '3 minutes', '5 minutes'], answer: 1 } },
    ]
  },
  {
    id: '3',
    title: 'Основы программирования (Python)',
    description: 'Изучите Python с нуля: переменные, циклы, функции, работа с данными. Курс для тех, кто хочет участвовать в хакатонах и олимпиадах по информатике.',
    level: 'Начальный',
    tags: ['Программирование', 'STEM'],
    image: '🐍',
    lessons: [
      { id: '3-1', title: 'Введение в Python: переменные и типы', content: 'Python — один из самых популярных языков в мире, используется в data science, веб-разработке и автоматизации.\n\n**Переменные:**\n```python\nname = "Айгерим"    # строка (str)\nage = 16            # целое число (int)\ngpa = 4.8           # дробное число (float)\nis_student = True   # булево (bool)\n```\n\n**Ввод и вывод:**\n```python\nname = input("Введите имя: ")\nprint(f"Привет, {name}!")\n```\n\n**Операции:**\n```python\nx = 10\ny = 3\nprint(x + y)   # 13\nprint(x ** y)  # 1000 (степень)\nprint(x % y)   # 1 (остаток)\n```\n\nПопробуйте написать программу, которая спрашивает ваш год рождения и выводит возраст!', video_url: '', order_index: 1, quiz: { question: 'Что выведет print(10 % 3)?', options: ['3', '1', '0', '10'], answer: 1 } },
      { id: '3-2', title: 'Условия и циклы', content: '**Условный оператор if:**\n```python\ngrade = 85\nif grade >= 90:\n    print("Отлично!")\nelif grade >= 70:\n    print("Хорошо!")\nelse:\n    print("Нужно постараться")\n```\n\n**Цикл for:**\n```python\nfor i in range(1, 6):\n    print(i)  # выводит 1 2 3 4 5\n\n# Цикл по списку\nfruits = ["яблоко", "банан", "вишня"]\nfor fruit in fruits:\n    print(fruit)\n```\n\n**Цикл while:**\n```python\ncount = 0\nwhile count < 5:\n    print(count)\n    count += 1\n```\n\n**Задача:** напишите программу, которая находит сумму чисел от 1 до 100.', video_url: '', order_index: 2, quiz: { question: 'Что выведет: for i in range(3): print(i)?', options: ['1 2 3', '0 1 2', '0 1 2 3', '1 2'], answer: 1 } },
      { id: '3-3', title: 'Функции и списки', content: '**Функции** — способ переиспользовать код:\n```python\ndef greet(name, language="ru"):\n    if language == "en":\n        return f"Hello, {name}!"\n    return f"Привет, {name}!"\n\nprint(greet("Алия"))       # Привет, Алия!\nprint(greet("Aliya", "en"))  # Hello, Aliya!\n```\n\n**Списки:**\n```python\nscores = [85, 92, 78, 95, 88]\n\n# Полезные методы\nscores.append(100)      # добавить\nscores.sort()           # сортировать\nprint(max(scores))      # максимум\nprint(sum(scores)/len(scores))  # среднее\n\n# List comprehension (мощный инструмент!)\nsquares = [x**2 for x in range(1, 6)]\nprint(squares)  # [1, 4, 9, 16, 25]\n```', video_url: '', order_index: 3, quiz: { question: 'Что выведет: print([x*2 for x in range(3)])?', options: ['[0,1,2]', '[0,2,4]', '[2,4,6]', '[1,2,3]'], answer: 1 } },
      { id: '3-4', title: 'Словари и работа с данными', content: '**Словари (dict)** — хранят данные в формате ключ: значение:\n```python\nstudent = {\n    "name": "Данияр",\n    "grade": 11,\n    "subjects": ["математика", "физика"],\n    "gpa": 4.9\n}\n\nprint(student["name"])     # Данияр\nstudent["city"] = "Алматы"  # добавить ключ\n\n# Перебор\nfor key, value in student.items():\n    print(f"{key}: {value}")\n```\n\n**Практический проект:**\n```python\n# Анализ оценок класса\nstudents = [\n    {"name": "Алия", "score": 95},\n    {"name": "Берик", "score": 87},\n    {"name": "Дина", "score": 92},\n]\n\nbest = max(students, key=lambda s: s["score"])\nprint(f"Лучший ученик: {best[\'name\']} ({best[\'score\']})")\n```', video_url: '', order_index: 4, quiz: { question: 'Как добавить ключ "age":16 в словарь d?', options: ['d.add("age", 16)', 'd["age"] = 16', 'd.append("age", 16)', 'add(d, "age", 16)'], answer: 1 } },
    ]
  },
]

export const CATEGORIES = ['Все', 'Олимпиада', 'Хакатон', 'Стипендия', 'Летняя школа', 'Конкурс', 'Исследования', 'Волонтёрство', 'Стажировка']
export const TAGS = ['Все', 'STEM', 'Бизнес', 'Программирование', 'Наука', 'Социальное влияние', 'Финансы', 'Английский', 'Поступление']
export const GRADES = ['Все', '8', '9', '10', '11']
export const INTERESTS = ['STEM', 'Бизнес', 'Программирование', 'Наука', 'Социальное влияние', 'Финансы', 'Английский', 'Поступление в университет', 'Математика', 'Физика', 'Биология']
export const GOALS = ['Поступить в топ-университет', 'Выиграть олимпиаду', 'Получить стипендию', 'Найти стажировку', 'Изучить программирование', 'Улучшить английский', 'Стать предпринимателем']
